### ISSUE TITLE
should "break" apply to a spawn statement or task block?

### ISSUE THREAD

**Issue by nelsc** [wg14-cplex/epp#12]

**Comment by nelsc** [comment]
If not, then a "break" in one of these constructs would be an error -- unless it's contained in a nested loop or switch.

On the other hand, I can't see the sense of making "continue" apply to one of these, so that would still be an error. But of course there's also a precedent for "break" and "continue" to apply to different sets of statements.

**Comment by phalpern** [comment]
Here's a problem I see with using "break" to exit a spawn block. The 
following would be legal:

```
for (int i = 0; i < n; ++i)
     _Task_parallel _Spawn {
        if (f(i))
            break;
        code
        code
     }
```

Note that the break statement does not end the loop.  However, if similar code were 
rewritten as a parallel for loop:

```
_Task_parallel for (int i = 0; i < n; ++i) {
    if (f(i))
        break;
    code
    code
}
```

, the `break` statement would be illegal.  Ironically, a `continue` would 
work in the second case and give the same results as the `break` in the 
first case, whereas the `continue` is illegal in the first case. This 
seems a little confusing to me.

**Comment by phalpern** [comment]
Perhaps we should allow `continue` to be used to _jump to the end_ of a spawn block or task block.  That would make it consistent with the body of a parallel `for` loop and avoid the above confusion.  Exiting a spawn block or task block via `break` would remain illegal.

**Comment by nelsc** [comment]
To me, "continue" means "terminate the current iteration", whereas "break" means "terminate the current (relevant) statement". That's consistent with the fact that today, "continue" works only with a loop, whereas "break" works with a switch as well.

So the idea of having "continue" apply to a non-loop strikes me as more novel and potentially confusing than having "break" do that.

**Comment by BlaineGarst** [comment]
It seems to me that we should consider
  _Task_parallel break;
or even
  _Task_parallel return;
so that the new special semantics has a new special syntax rather than asking folks to scratch their heads about what it might or should mean when it is simply given a new meaning.

**Comment by nelsc** [comment]
> It seems to me that we should consider
> _Task_parallel break;

I'm actually less concerned about providing the functionality of terminating one of these constructs than I am about having "break" simply be an error in certain contexts.

**Comment by nelsc** [comment]
The consensus supports leaving "break" as being an error in these contexts.
