### ISSUE TITLE
is three-token lookahead OK for "_Task_parallel _Call"?

### ISSUE THREAD

**Issue by nelsc** [wg14-cplex/epp#14]
If "_Task_parallel _Call" is seen where either a statement or declaration is expected, the next token needs to be considered to decide between them. C++ already has far more serious lookahead issues than that, but for C, this could be considered a serious new problem.

**Comment by nelsc** [comment]
We specifically want to ask Rajan Bhakta for his feedback on implementing CPLEX in a one-pass compiler; this issue may concern him.

**Comment by nelsc** [comment]
If this were considered to be a problem, then the solution would be to use a different keyword for the declaration than for the statement -- probably something like "_Task _Callable" for the declaration, keeping "_Task _Call" for the statement.

**Comment by kkwli** [comment]
I checked our one-pass compiler and discussed it with Rajan Bhakta.  The infrastructure in the compiler should be able to handle the proposed syntax.

**Comment by nelsc** [comment]
This condition (which wasn't necessarily a problem to begin with) was eliminated with the resolution of issue #15.
