### ISSUE TITLE
The _Capture keyword should be renamed

### ISSUE THREAD

**Issue by phalpern** [wg14-cplex/epp#20]
The keyword `_Capture` implies a general closure, which is not what the CPLEX WP describes.  We should consider a different keyword so that we don't interfere with the definition of a real closure facility later.

Some possibilities:
- `_Firstprivate`  -- this is the term used by OpenMP.  I hate it, but it has precedence.
- `_Private` -- I don't this one, either, because it has too many incorrect implications.
- `_Local`
- `_Copy`
- `_LocalCopy` -- This might be the most descriptive of what is actually going on, but I worry that we might want to add syntax later for non-copy local renaming of variables and might not want to introduce a new keyword.

**Comment by nelsc** [comment]
In a CPLEX straw poll, the preference was evenly split between "_LocalCopy" and "_CopyIn"; no alternative had any support (not even "_Capture" or "_Firstprivate").

It should be noted that "_CopyIn" occurred only verbally, and at no time was there mention of details of its spelling.

**Comment by nelsc** [comment]
Personally, I absolutely hate CamelCase identifiers. A little less subjectively, if the "primary" keyword is in camel-case, exactly how should the "pretty" macro for it be spelled? So I would vastly prefer either "_Localcopy" or "_Local_copy" to "_LocalCopy", for example.

**Comment by jeffhammond** [comment]
:-1: to CamelCase, i.e. :+1: to Clark's proposal.  I can't think of any other place where ISO C uses :camel::camel::camel: and we should not aspire to be the first.

**Comment by phalpern** [comment]
I'm beginning to lean towards _Copyin or _Copy_in, though _Local_copy or _Localcopy would both work for me.  I'm pretty sure I voted the other way at the meeting.

**Comment by nelsc** [comment]
At today's meeting, there was no objection to "_Copy_in".
