### ISSUE TITLE
_Task_parallel keyword should be shortened

### ISSUE THREAD

**Issue by phalpern** [wg14-cplex/epp#21]
The verbosity of the `Task_parallel` keyword has been a problem for me when writing examples.  It is cumbersome, especially when combined with the additional keywords `_Spawn`, `_Call`, and `for`.  I recommend that we shorten it to either `_Task` or `_Parallel`.  The first makes it clear that the type of parallelism is _task_ parallelism.  The second is, well, more obvious.  I prefer `_Task` to `_Parallel` as the term "parallel" can be overused and thus becomes ambiguous.  Thus, I am suggesting these changes:
- `_Task_parallel _Spawn`   becomes `_Task _Spawn`
- `_Task_parallel _Call`      becomes `_Task _Call`
- `_Task_parallel for`         becomes `_Task for`

**Comment by nelsc** [comment]
I'm OK with shortening "_Task_parallel" to "_Task". But I would strongly object to shortening it to "_Parallel", for example. If the user says "I just want these things to be done in parallel", without any sort of qualification, then the implementation should be free to use a method that doesn't have all the overhead of task-local storage -- such as a GPU.

**Comment by BlaineGarst** [comment]
_Parallel makes more sense to me than _Task.  Back in my kernel days "task" meant process and is already pretty overloaded.

**Comment by nelsc** [comment]
In a CPLEX straw poll, "_Task" was favored over "_Task_parallel" by a 4-to-3 vote. I have made the corresponding change to the WD, so people can see what it looks like, but the issue is not considered closed.

**Comment by nelsc** [comment]
At today's meeting, the change was accepted with no objection.
