### ISSUE TITLE
we should have a feature-test macro

### ISSUE THREAD

**Issue by nelsc** [wg14-cplex/epp#23]

**Comment by BlaineGarst** [comment]
Absolutely!

Perhaps even subfeatures??

**Comment by jeffhammond** [comment]
I'm a huge fan of these, particularly when they are actually implemented correctly (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58016).

**Comment by nelsc** [comment]
I'm thinking of adding a new clause for this, along these lines:

5 Predefined macro names
The following macro name is defined by the implementation:
`__STDC_PARALLEL_EXT__`: The integer constant 201601.

(Naturally, the value of the macro would be kept in sync with the document date.)
