### ISSUE TITLE
how does FENV_ACCESS affect reduction operations?

### ISSUE THREAD

**Issue by nelsc** [wg14-cplex/epp#4]

**Comment by nelsc** [comment]
See the WG14 reflector thread starting with http://www.open-std.org/jtc1/sc22/wg14/14029

**Comment by ncopty** [comment]
The OpenMP 4.5 specification says the following about reduction (see http://www.openmp.org/mp-documents/openmp-4.5.pdf, p. 205, lines 23-27):

The location in the OpenMP program at which the values are combined and the order in which the values are combined are unspecified. Therefore, when comparing sequential and parallel runs, or when comparing one parallel run to another (even if the number of threads used is the same), there is no guarantee that bit-identical results will be obtained or that side effects (such as floating-point exceptions) will be identical or take place at the same location in the OpenMP program.

**Comment by phalpern** [comment]
In Cilk Plus, the floating-point environment at the point of a spawn applies to both the parent and child tasks of the spawn.  If, however, one of the two tasks changes the FPE (including setting a floating-point exception), then the FPE at the point immediately after a sync is indeterminately the FPE of the child or parent.

Similarly, the FPE on entering a _Cilk_for (parallel for loop) is used for all iterations of the for loop, but changing the FPE in any iteration (including setting a FP exception) will result in an indeterminate change in other iterations and in the continuation of the program after the loop.

This seems like reasonable behavior to me.

**Comment by nelsc** [comment]
I have added a note to the WD spelling out what is believed to be true.
