### ISSUE TITLE
what if an object of reduction type is dynamically allocated?

### ISSUE THREAD

**Issue by nelsc** [wg14-cplex/epp#5]

**Comment by nelsc** [comment]
This may be related to issue #6.

**Comment by phalpern** [comment]
We should allow static and automatic storage, but not dynamic storage duration for reduction objects.

**Comment by jeffhammond** [comment]
What is the reason for this restriction?  I don't have a compelling reason to put such objects on the heap, but since it is an exception to the rule (most C objects are permitted to use all three storage types mentioned), someone will eventually try to do this and wonder why.

**Comment by phalpern** [comment]
There are two reasons for this restriction:
- An efficient implementation of reduction variables depends on having the lifetime of the root view neatly nested within or around parallel constructs.  In the code below, the root view is created in one thread, but might not be the view within that thread.  Conversely, the root view might be the same as the view within the creating thread, but is not the view of the main thread:

``` C
    typedef _Reduction intadd { _Type : int, _Combiner : += } intadd;
    intadd *rp;
    _Task_parallel _Block {
        _Task_parallel _Spawn {
            rp = (intadd*) malloc(sizeof(intadd));
            *rp = 0;   // Problem: Is this the root view?
        }
        ...
    }
    int sum = *rp;  // Problem: this might not be the root view
```
- Unlike ordinary variables, reduction variables almost certainly need dynamic initialization and tear-down.  Casting the return pointer from `malloc()` skips this initialization.

**Comment by nelsc** [comment]
If we were to impose this restriction, violating it would have to cause UB, since there's no reliable way to detect it at translation time.

**Comment by nelsc** [comment]
As of the 2015-12-21 meeting, I speculatively added a description of this UB to the WD. As a courtesy, this issue is being left open, to give more time for consideration. But unless someone comes up with a specific argument to make a change, this issue will be closed soon.
