### ISSUE TITLE
how is the root view of a reduction initialized by default?

### ISSUE THREAD

**Issue by nelsc** [wg14-cplex/epp#6]
In the proposal that was (mostly) accepted, if the reduction object declaration had no explicit initializer, the root view would be initialized the same way as a task-specific view.

When the group discussed it, there was discomfort at adding constructor-like functionality to C. But I'm not sure whether that discomfort applied only when the initializer is a function. In other words, if the initializer is a value, is default initialization of the root view still a bad idea? Or we really prefer it to be uninitialized?

**Comment by phalpern** [comment]
In Cilk Plus C code, a value for the root view is always supplied by the caller at the point that the reducer is created.

In Cilk Plus C++ code, the caller can provide one or more constructor arguments for the root view.  However, if no arguments are provided, the root view is NOT default-constructed but is instead constructed using the initializer supplied in the definition of the reducer.  This is deliberately inconsistent, but is almost always what the programmer wants.  However, this IS a constructor and is therefore C++ specific.
